spring.application.name=crm
spring.datasource.url=jdbc:mysql://localhost:3306/loyalty_db
spring.datasource.username=root
spring.datasource.password=dharshana05

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

loyalty.discount.threshold=500
loyalty.discount.min-percent=2
loyalty.discount.max-percent=20
loyalty.profit.estimated-margin-percent=28
loyalty.profit.min-retained-margin-percent=10
loyalty.profit.max-discount-share-of-profit-percent=50
